### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by jlopp** [shocknet/singles-api#1]
Looks like the cert for https://singles.shock.network/ is out of date; please renew it ASAP.

**Comment by jlopp** [comment]
I'm removing the link to your site from https://www.lopp.net/lightning-information.html since I haven't heard back. If you fix the SSL cert you can make a PR to https://github.com/jlopp/lopp.net/blob/master/lightning-information.html to have it re-added.

**Comment by shocknet-justin** [comment]
Sorry, for some reason didn't get alerted to this. 

Service down, repurposed the server... will launch a more robust 2.0 hopefully.
